### ISSUE TITLE
Having trouble with fonts not being found on live production

### ISSUE THREAD

**Issue by rylanharper** [nuxt/fonts#174]
Hey! Very cool package. I'm using this for an open-source Nuxt project I am working on behind the scenes, but I am running into issues when deploying to live production via `Netlify`.. 

Oddly enough, `Netlify` shows that the fonts are downloaded and cached `[success] [@nuxt/fonts] Fonts downloaded and cached.`, but when I navigate to my site I get the following error:
```
GET https://yeren.netlify.app/_fonts/-F63fjptAgt5VM-kVkqdyU8n5is-60MhQVXoUT.woff net::ERR_ABORTED 404 (Not Found)
GET https://yeren.netlify.app/_fonts/-F63fjptAgt5VM-kVkqdyU8n1i8q131nj-o-jzNqqYFBmI.woff2 net::ERR_ABORTED 404 (Not Found)
```

My `nuxt.config` looks like this:
```
modules: [
  '@nuxt/fonts',
],

fonts: {
  families: [
    { name: 'IBM Plex Mono', provider: 'google', weights: [400, 500, 600] },
    { name: 'IBM Plex Sans', provider: 'google', weights: [400, 500, 600] }
  ]
},
```

Perhaps this is an issue with my config? Any help would be appreciated:)

**Comment by rylanharper** [comment]
Hmm so I have tried various solutions..

```
fonts: {
  families: [
    { name: 'IBM Plex Mono', provider: 'google' },
    { name: 'IBM Plex Sans', provider: 'google' }
  ],
  defaults: {
    weights: [400, 500, 600]
  }
}
```

`tailwind.config.ts`
```
import type { Config } from 'tailwindcss'

export default <Partial<Config>>{
  theme: {
    extend: {
      fontFamily: {
        sans: ['IBM Plex Sans'],
        mono: ['IBM Plex Mono']
      }
    }
  }
}
```

This should work, but it simply doesn't and fonts are not downloading/caching correctly..

**Comment by danielroe** [comment]
The issue is a Nitro/Nuxt bug with files beginning with `-`. It should be fixed in the latest Nuxt/Nitro versions - can you try updating your lockfile and seeing if the issue reoccurs?

**Comment by rylanharper** [comment]
@danielroe unfortunately the problem still occurs when upgrading the latest version of Nuxt. Here are the relevant packages in my `package.json`:
```
"@nuxt/fonts": "^0.7.0",
"nuxt": "^3.12.1",
```

**Comment by danielroe** [comment]
What happens if you pin your Nuxt Kit version?

**Comment by rylanharper** [comment]
I pinned the Nuxt version to `3.12.1` and updated the lock file again.. Same result, the fonts do not download properly on live production..

Here is a [StackBlitz](https://stackblitz.com/edit/nuxt-starter-rt8zew?file=nuxt.config.ts) of the issue. The error shows up in the dev console, stating that the fonts cannot be downloaded:
```
ERROR  Could not download google font metadata. @nuxt/fonts will not be able to inject @font-face rules for google.
ERROR  Could not download fontshare font metadata. @nuxt/fonts will not be able to inject @font-face rules for fontshare.
```

Although, the monospace font is displaying correctly within the StackBlitz environment so idk whats going on..

**Comment by rylanharper** [comment]
Hey @danielroe, any update on this? 🤓

No rush, just checking if I should leave out `@nuxt/fonts` for the time being and just manually import/download some font styles?

**Comment by rylanharper** [comment]
I know you're going to hate me, but the issue still persists after upgrading to `^0.7.1`.. Still seems to be an issue with those mono fonts and having a `-`. I've updated the [Stackblitz](https://stackblitz.com/edit/nuxt-starter-rt8zew) to include version `^0.7.1`.

Here is a current screenshot:
<img width="2560" alt="Screenshot 2024-06-25 at 9 13 20 AM" src="https://github.com/nuxt/fonts/assets/16216160/0aad0242-e41c-468e-8dc6-7152ab5951f1">


And here is the font options within my `nuxt.config.ts`:
```
fonts: {
  families: [
    { name: 'IBM Plex Mono', provider: 'google' },
    { name: 'IBM Plex Sans', provider: 'google' }
  ],
  defaults: {
    weights: [400, 500, 600]
  }
}
```

**Comment by danielroe** [comment]
Sorry about that! I've resolved and will be releasing shortly.

**Comment by rylanharper** [comment]
No worries man. You and the Nuxt team are doing an amazing job!

**Comment by jh0ker** [comment]
@danielroe reminder that this is still happening, I patched it on my end but a release would probably be good.

**Comment by danielroe** [comment]
Released! ✅ Let me know if you encounter any issues.
